In [2]:
import numpy as np 
#creating numpy arrays
my_list=[-1,0,1]
my_list

[-1, 0, 1]

In [4]:
my_array=np.array(my_list)
my_array

array([-1,  0,  1])

In [8]:
print(type(my_array))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [9]:
my_array2=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
my_array2

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [11]:
creat_array=np.array(my_array2)
creat_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
type(creat_array)

numpy.ndarray

In [13]:
tpl=(1,2,3,4,5)
type(tpl)

tuple

In [35]:
#creating arrays using numpy built in function
arr=np.arange(0,16)
print(arr)
print(arr.shape)
print(arr.reshape(4,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [28]:
arr2=np.linspace(1,20,100, retstep=True)
arr2

(array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
         1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
         2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
         3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
         4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
         5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
         6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
         7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
         8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
         9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
        10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
        11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
        12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
        13.47474747, 13.66666667, 13.85858586, 14.0

In [41]:
#random function
#follows normal distributation
rand_func=np.random.rand(1,100)
print(rand_func)



[[0.82723031 0.17324334 0.67452787 0.38311203 0.59083916 0.47390083
  0.35692582 0.89648151 0.19063073 0.25118048 0.58965505 0.15812703
  0.61254911 0.97130583 0.0422164  0.39094216 0.40180587 0.61691883
  0.62611989 0.80425421 0.19418828 0.09178203 0.60388942 0.62630655
  0.15530029 0.11635238 0.96191598 0.78532671 0.95506778 0.95685453
  0.915278   0.63429916 0.4400651  0.74108155 0.37643147 0.45906831
  0.84719544 0.19353047 0.66207307 0.09430685 0.5653506  0.79269315
  0.8871137  0.77107817 0.27897107 0.71826035 0.14958104 0.93560356
  0.41597939 0.67213103 0.22398976 0.60155323 0.07831707 0.8328341
  0.86525325 0.06968288 0.02102783 0.65107927 0.97781731 0.87687012
  0.34480484 0.55848381 0.15884152 0.3721893  0.08355453 0.68651304
  0.38054893 0.23335663 0.04880997 0.58103959 0.23597483 0.34797941
  0.79556327 0.3922185  0.83884472 0.21905632 0.39654442 0.3482917
  0.79258741 0.91574356 0.87302031 0.6023139  0.51257723 0.97255929
  0.51695251 0.91842961 0.12123856 0.40229578 0.21

In [42]:
randint_func=np.random.randint(0,20,3)
print(randint_func)

[ 4 18 13]


In [51]:
x=np.random.randint(100,500,100).reshape(10,10)
x

array([[341, 383, 334, 399, 456, 438, 465, 170, 298, 282],
       [100, 450, 475, 214, 204, 309, 398, 292, 272, 187],
       [333, 179, 433, 160, 276, 369, 372, 434, 195, 100],
       [210, 238, 241, 262, 269, 322, 261, 449, 373, 162],
       [186, 316, 374, 229, 355, 274, 287, 243, 286, 399],
       [306, 296, 218, 498, 128, 397, 330, 181, 178, 333],
       [112, 440, 264, 476, 187, 101, 485, 285, 171, 269],
       [229, 296, 349, 394, 290, 138, 377, 296, 219, 199],
       [447, 126, 320, 368, 448, 460, 137, 113, 437, 115],
       [153, 309, 149, 196, 381, 378, 484, 261, 121, 249]])

In [52]:
#argmax,argmin,max,min function.
x.argmax()

53

In [53]:
x.argmin()

10

In [54]:
x.max()

498

In [55]:
x.min()

100

In [65]:
#indexing and slicing
array_1d=np.array([2,0,12,34,13,87,45])
array_1d[0:3]

array([ 2,  0, 12])

In [67]:
array_1d[-2]

87

In [70]:
#broadcasting 
array_2d=np.arange(0,100)
array_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [71]:
x=array_2d.reshape(10,10)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [73]:
x[2]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [74]:
x[5][2]

52

In [75]:
#broadcasting
x[0:4]=10

In [76]:
x

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [82]:
#ones
one_f=np.ones((4,4), dtype=int)
one_f

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [83]:
zero_fun=np.zeros((4,4), dtype=int)
zero_fun

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [85]:
#applying condition
con_fun=np.arange(1,11)
print(con_fun)
print(con_fun>3)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False  True  True  True  True  True  True  True]


In [86]:
print(con_fun%2)

[1 0 1 0 1 0 1 0 1 0]


In [94]:
#arithmatic operation
y=np.arange(0,16)
z=np.random.randint(1,2,16)
print(y)
print(z)
print(y+z)
print(y*z)
print(y/z)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [97]:
#universal function
array=np.arange(0,16)
print(np.sqrt(array))
print(np.sin(array))
print(type(array))


[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292  0.42016704  0.99060736  0.65028784]
<class 'numpy.ndarray'>


In [100]:
#numpy array copy vs view
data=np.array([1,2,3,4,5,6])
copy_data=data.copy()
data[0]=7
print(data)


[7 2 3 4 5 6]
[7 2 3 4 5 6]


In [105]:
data2=np.array([3,5,7,9,10])
view_data=data2.view()
data2[2]=4
print(data2)
print(view_data)

[ 3  5  4  9 10]
[ 3  5  4  9 10]


In [106]:
#numpy joining
#1D array
b=np.array([1,2,3,4,5,6,7,8,9,10])
c=np.array([1,2,3,4,5,6,7,8,9,10])
concate_fun=np.concatenate((b,c))
print(concate_fun)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


In [109]:
#2D array
arr_2d_1=[[1,2,3],[4,5,6]]
arr_2d_2=[[7,8,9],[10,11,12]]
conct_arr_2d=np.concatenate((arr_2d_1, arr_2d_2), axis=0)
print(conct_arr_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [112]:
#array_split function
new_array=np.array([1,2,3,4,5,6,7,8,9,10])
x_split=np.array_split(new_array,3)
x_split

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [113]:
#numpy searching array
new_array=np.array([1,2,3,4,5,6,7,8,9,10])
x=np.where(new_array==5)
print(x)

(array([4], dtype=int64),)


In [ ]:
#numpy sorting
new_array=np.array([11,26,23,40,57,62,79,8,9,10])